name: Zomoto clone app build
on:
  push:
    branches:
      - 'master'

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install

    - name: Set image tag with timestamp
      id: set_tag
      run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/myfirstimage:${{github.run_number}}"
          #IMAGE_TAG="snagireddy9/myfirstimage:$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  
          echo "${{github.run_number}}"

    - name: Build the Docker Image
      run: |
           #IMAGE_TAG="myfirstimage:$(date +'%Y-%m-%d_%H-%M-%S')"
           echo "Building image with tag $IMAGE_TAG"
           docker build . --file Dockerfile --tag $IMAGE_TAG
           #docker build . --file Dockerfile 
    
